Feature settings to api sync
apfaff/sweather pull request #1
Opened 2018-08-18 15:16 UTC by ksidpen

get some sync 😘

2018-08-20 08:42 UTC, apfaff requested changes
Ich habe auch überlegt, nur einmal einen Request an den Server zu senden. Beispielsweise mit onClick auf den OK-Button. 
So spart man sich die debounces und hat nicht so ein wirrwarr.. 

Das macht natürlich die Buttonlose Navigation ein bischen kaputt, ist aber vielleicht ein bischen einfacher zu verstehen und zu vermitteln.

Bevor du angefangen hast, habe ich noch einmal ein paar Änderungen in den `master` gepusht, der die debounces entfernt und die Logik auf den OK-Button click auslagert. Habe dir vergessen zu sagen, dass du vielleicht noch einmal pullen solltest 😅

2018-08-20 08:42 UTC, apfaff commented on src/client/screens/settings/Settings.js
> +        return
Hier gibts nen kleines Problem.. Hat man die Permissions nicht, springt man komplett aus der Funktion raus und aktualisiert den state (`this.state.notifications`) nicht. Wenn man sich anstatt dem `return` eine Flag setzt (bspw. `permissions`), wird in der sync Funktion anschließend trotzdem versucht eine Push zu senden. Da müsste man noch einmal drauf eingehen.

2018-08-20 09:41 UTC, ksidpen commented
🎉

2018-08-24 10:42 UTC, apfaff approved these changes

2018-08-24 10:43 UTC, merged